[package]

name = "hw"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
os_info = "3.8.2"
serde = "1.0.203"
sysinfo = "0.30.12"
tokio = {version = "1.35.1", features = ["full"]}
winreg = "0.52.0"
wmi = "0.13.2"
